openapi: 3.0.0
info:
  title: DLM
  version: 1.0.0
paths: {}
components:
  schemas:
    Action:
      type: object
      additionalProperties: false
      properties:
        CrossRegionCopy:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/CrossRegionCopyAction'
        Name:
          type: string
      required:
        - CrossRegionCopy
        - Name
    Exclusions:
      type: object
      additionalProperties: false
      properties:
        ExcludeTags:
          $ref: '#/components/schemas/ExcludeTags'
        ExcludeVolumeTypes:
          $ref: '#/components/schemas/ExcludeVolumeTypesList'
        ExcludeBootVolumes:
          type: boolean
    ArchiveRule:
      type: object
      additionalProperties: false
      properties:
        RetainRule:
          $ref: '#/components/schemas/ArchiveRetainRule'
      required:
        - RetainRule
    ExcludeVolumeTypesList:
      type: object
      additionalProperties: false
    DeprecateRule:
      type: object
      additionalProperties: false
      properties:
        IntervalUnit:
          type: string
        Count:
          type: integer
        Interval:
          type: integer
    CrossRegionCopyDeprecateRule:
      type: object
      additionalProperties: false
      properties:
        IntervalUnit:
          type: string
        Interval:
          type: integer
      required:
        - IntervalUnit
        - Interval
    CreateRule:
      type: object
      additionalProperties: false
      properties:
        IntervalUnit:
          type: string
        Scripts:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Script'
        Times:
          type: array
          uniqueItems: false
          items:
            type: string
        CronExpression:
          type: string
        Interval:
          type: integer
        Location:
          type: string
    PolicyDetails:
      type: object
      additionalProperties: false
      properties:
        PolicyLanguage:
          type: string
        ResourceTypes:
          type: array
          uniqueItems: false
          items:
            type: string
        Schedules:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Schedule'
        PolicyType:
          type: string
        CreateInterval:
          type: integer
        Parameters:
          $ref: '#/components/schemas/Parameters'
        ExtendDeletion:
          type: boolean
        Exclusions:
          $ref: '#/components/schemas/Exclusions'
        Actions:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Action'
        ResourceType:
          type: string
        RetainInterval:
          type: integer
        EventSource:
          $ref: '#/components/schemas/EventSource'
        CrossRegionCopyTargets:
          $ref: '#/components/schemas/CrossRegionCopyTargets'
        TargetTags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
        ResourceLocations:
          type: array
          uniqueItems: false
          items:
            type: string
        CopyTags:
          type: boolean
    Script:
      type: object
      additionalProperties: false
      properties:
        ExecutionHandlerService:
          type: string
        ExecutionTimeout:
          type: integer
        Stages:
          type: array
          uniqueItems: false
          items:
            type: string
        ExecutionHandler:
          type: string
        MaximumRetryCount:
          type: integer
        ExecuteOperationOnScriptFailure:
          type: boolean
    Parameters:
      type: object
      additionalProperties: false
      properties:
        ExcludeBootVolume:
          type: boolean
        NoReboot:
          type: boolean
        ExcludeDataVolumeTags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
    CrossRegionCopyRule:
      type: object
      additionalProperties: false
      properties:
        TargetRegion:
          type: string
        Target:
          type: string
        DeprecateRule:
          $ref: '#/components/schemas/CrossRegionCopyDeprecateRule'
        Encrypted:
          type: boolean
        CmkArn:
          type: string
        RetainRule:
          $ref: '#/components/schemas/CrossRegionCopyRetainRule'
        CopyTags:
          type: boolean
      required:
        - Encrypted
    EncryptionConfiguration:
      type: object
      additionalProperties: false
      properties:
        Encrypted:
          type: boolean
        CmkArn:
          type: string
      required:
        - Encrypted
    CrossRegionCopyRetainRule:
      type: object
      additionalProperties: false
      properties:
        IntervalUnit:
          type: string
        Interval:
          type: integer
      required:
        - IntervalUnit
        - Interval
    ExcludeTags:
      type: object
      additionalProperties: false
    EventParameters:
      type: object
      additionalProperties: false
      properties:
        DescriptionRegex:
          type: string
        EventType:
          type: string
        SnapshotOwner:
          type: array
          uniqueItems: false
          items:
            type: string
      required:
        - EventType
        - SnapshotOwner
    RetainRule:
      type: object
      additionalProperties: false
      properties:
        IntervalUnit:
          type: string
        Count:
          type: integer
        Interval:
          type: integer
    CrossRegionCopyAction:
      type: object
      additionalProperties: false
      properties:
        Target:
          type: string
        EncryptionConfiguration:
          $ref: '#/components/schemas/EncryptionConfiguration'
        RetainRule:
          $ref: '#/components/schemas/CrossRegionCopyRetainRule'
      required:
        - Target
        - EncryptionConfiguration
    EventSource:
      type: object
      additionalProperties: false
      properties:
        Type:
          type: string
        Parameters:
          $ref: '#/components/schemas/EventParameters'
      required:
        - Type
    ArchiveRetainRule:
      type: object
      additionalProperties: false
      properties:
        RetentionArchiveTier:
          $ref: '#/components/schemas/RetentionArchiveTier'
      required:
        - RetentionArchiveTier
    CrossRegionCopyTargets:
      type: object
      additionalProperties: false
    Schedule:
      type: object
      additionalProperties: false
      properties:
        ShareRules:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/ShareRule'
        DeprecateRule:
          $ref: '#/components/schemas/DeprecateRule'
        TagsToAdd:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
        CreateRule:
          $ref: '#/components/schemas/CreateRule'
        VariableTags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
        FastRestoreRule:
          $ref: '#/components/schemas/FastRestoreRule'
        ArchiveRule:
          $ref: '#/components/schemas/ArchiveRule'
        RetainRule:
          $ref: '#/components/schemas/RetainRule'
        CrossRegionCopyRules:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/CrossRegionCopyRule'
        Name:
          type: string
        CopyTags:
          type: boolean
    FastRestoreRule:
      type: object
      additionalProperties: false
      properties:
        IntervalUnit:
          type: string
        Count:
          type: integer
        AvailabilityZones:
          type: array
          uniqueItems: false
          items:
            type: string
        Interval:
          type: integer
    RetentionArchiveTier:
      type: object
      additionalProperties: false
      properties:
        IntervalUnit:
          type: string
        Count:
          type: integer
        Interval:
          type: integer
    Tag:
      type: object
      additionalProperties: false
      properties:
        Value:
          type: string
        Key:
          type: string
      required:
        - Value
        - Key
    ShareRule:
      type: object
      additionalProperties: false
      properties:
        TargetAccounts:
          type: array
          uniqueItems: false
          items:
            type: string
        UnshareIntervalUnit:
          type: string
        UnshareInterval:
          type: integer
    LifecyclePolicy:
      type: object
      properties:
        CreateInterval:
          type: integer
        Description:
          type: string
        ExtendDeletion:
          type: boolean
        Exclusions:
          $ref: '#/components/schemas/Exclusions'
        RetainInterval:
          type: integer
        ExecutionRoleArn:
          type: string
        DefaultPolicy:
          type: string
        State:
          type: string
        CrossRegionCopyTargets:
          $ref: '#/components/schemas/CrossRegionCopyTargets'
        PolicyDetails:
          $ref: '#/components/schemas/PolicyDetails'
        Id:
          type: string
        Arn:
          type: string
        Tags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
        CopyTags:
          type: boolean
      x-stackql-resource-name: lifecycle_policy
      x-stackql-primaryIdentifier:
        - Id
      x-read-only-properties:
        - Id
        - Arn
  x-stackQL-resources:
    lifecycle_policies:
      name: lifecycle_policies
      id: aws.dlm.lifecycle_policies
      x-cfn-schema-name: LifecyclePolicy
      x-type: list
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as 
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::DLM::LifecyclePolicy'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Id') as 
                FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::DLM::LifecyclePolicy'
    lifecycle_policy:
      name: lifecycle_policy
      id: aws.dlm.lifecycle_policy
      x-cfn-schema-name: LifecyclePolicy
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.CreateInterval') as create_interval,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.ExtendDeletion') as extend_deletion,
              JSON_EXTRACT(Properties, '$.Exclusions') as exclusions,
              JSON_EXTRACT(Properties, '$.RetainInterval') as retain_interval,
              JSON_EXTRACT(Properties, '$.ExecutionRoleArn') as execution_role_arn,
              JSON_EXTRACT(Properties, '$.DefaultPolicy') as default_policy,
              JSON_EXTRACT(Properties, '$.State') as state,
              JSON_EXTRACT(Properties, '$.CrossRegionCopyTargets') as cross_region_copy_targets,
              JSON_EXTRACT(Properties, '$.PolicyDetails') as policy_details,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.CopyTags') as copy_tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::DLM::LifecyclePolicy'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'CreateInterval') as create_interval,
                json_extract_path_text(Properties, 'Description') as description,
                json_extract_path_text(Properties, 'ExtendDeletion') as extend_deletion,
                json_extract_path_text(Properties, 'Exclusions') as exclusions,
                json_extract_path_text(Properties, 'RetainInterval') as retain_interval,
                json_extract_path_text(Properties, 'ExecutionRoleArn') as execution_role_arn,
                json_extract_path_text(Properties, 'DefaultPolicy') as default_policy,
                json_extract_path_text(Properties, 'State') as state,
                json_extract_path_text(Properties, 'CrossRegionCopyTargets') as cross_region_copy_targets,
                json_extract_path_text(Properties, 'PolicyDetails') as policy_details,
                json_extract_path_text(Properties, 'Id') as id,
                json_extract_path_text(Properties, 'Arn') as arn,
                json_extract_path_text(Properties, 'Tags') as tags,
                json_extract_path_text(Properties, 'CopyTags') as copy_tags
                FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::DLM::LifecyclePolicy'
