openapi: 3.0.0
info:
  title: Elasticsearch
  version: 1.0.0
paths: {}
components:
  schemas:
    LogPublishingOption:
      type: object
      additionalProperties: false
      properties:
        CloudWatchLogsLogGroupArn:
          type: string
        Enabled:
          type: boolean
    ElasticsearchClusterConfig:
      type: object
      additionalProperties: false
      properties:
        InstanceCount:
          type: integer
        WarmEnabled:
          type: boolean
        WarmCount:
          type: integer
        DedicatedMasterEnabled:
          type: boolean
        ZoneAwarenessConfig:
          $ref: '#/components/schemas/ZoneAwarenessConfig'
        ColdStorageOptions:
          $ref: '#/components/schemas/ColdStorageOptions'
        DedicatedMasterCount:
          type: integer
        InstanceType:
          type: string
        WarmType:
          type: string
        ZoneAwarenessEnabled:
          type: boolean
        DedicatedMasterType:
          type: string
    VPCOptions:
      type: object
      additionalProperties: false
      properties:
        SecurityGroupIds:
          type: array
          uniqueItems: true
          items:
            type: string
        SubnetIds:
          type: array
          uniqueItems: true
          items:
            type: string
    SnapshotOptions:
      type: object
      additionalProperties: false
      properties:
        AutomatedSnapshotStartHour:
          type: integer
    ZoneAwarenessConfig:
      type: object
      additionalProperties: false
      properties:
        AvailabilityZoneCount:
          type: integer
    NodeToNodeEncryptionOptions:
      type: object
      additionalProperties: false
      properties:
        Enabled:
          type: boolean
    ColdStorageOptions:
      type: object
      additionalProperties: false
      properties:
        Enabled:
          type: boolean
    DomainEndpointOptions:
      type: object
      additionalProperties: false
      properties:
        CustomEndpointCertificateArn:
          type: string
        CustomEndpointEnabled:
          type: boolean
        EnforceHTTPS:
          type: boolean
        CustomEndpoint:
          type: string
        TLSSecurityPolicy:
          type: string
    CognitoOptions:
      type: object
      additionalProperties: false
      properties:
        Enabled:
          type: boolean
        IdentityPoolId:
          type: string
        UserPoolId:
          type: string
        RoleArn:
          type: string
    EBSOptions:
      type: object
      additionalProperties: false
      properties:
        EBSEnabled:
          type: boolean
        VolumeType:
          type: string
        Iops:
          type: integer
        VolumeSize:
          type: integer
    Tag:
      type: object
      additionalProperties: false
      properties:
        Value:
          type: string
        Key:
          type: string
      required:
        - Value
        - Key
    EncryptionAtRestOptions:
      type: object
      additionalProperties: false
      properties:
        KmsKeyId:
          type: string
        Enabled:
          type: boolean
    MasterUserOptions:
      type: object
      additionalProperties: false
      properties:
        MasterUserPassword:
          type: string
        MasterUserName:
          type: string
        MasterUserARN:
          type: string
    AdvancedSecurityOptionsInput:
      type: object
      additionalProperties: false
      properties:
        Enabled:
          type: boolean
        MasterUserOptions:
          $ref: '#/components/schemas/MasterUserOptions'
        AnonymousAuthEnabled:
          type: boolean
        InternalUserDatabaseEnabled:
          type: boolean
    Domain:
      type: object
      properties:
        ElasticsearchClusterConfig:
          $ref: '#/components/schemas/ElasticsearchClusterConfig'
        DomainName:
          type: string
        ElasticsearchVersion:
          type: string
        LogPublishingOptions:
          type: object
          x-patternProperties:
            '[a-zA-Z0-9]+':
              $ref: '#/components/schemas/LogPublishingOption'
        SnapshotOptions:
          $ref: '#/components/schemas/SnapshotOptions'
        VPCOptions:
          $ref: '#/components/schemas/VPCOptions'
        NodeToNodeEncryptionOptions:
          $ref: '#/components/schemas/NodeToNodeEncryptionOptions'
        AccessPolicies:
          type: object
        DomainEndpointOptions:
          $ref: '#/components/schemas/DomainEndpointOptions'
        DomainArn:
          type: string
        CognitoOptions:
          $ref: '#/components/schemas/CognitoOptions'
        AdvancedOptions:
          type: object
          x-patternProperties:
            '[a-zA-Z0-9]+':
              type: string
        AdvancedSecurityOptions:
          $ref: '#/components/schemas/AdvancedSecurityOptionsInput'
        DomainEndpoint:
          type: string
        EBSOptions:
          $ref: '#/components/schemas/EBSOptions'
        Id:
          type: string
        Arn:
          type: string
        EncryptionAtRestOptions:
          $ref: '#/components/schemas/EncryptionAtRestOptions'
        Tags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
      x-stackql-resource-name: domain
      x-stackql-primaryIdentifier:
        - Id
  x-stackQL-resources:
    domains:
      name: domains
      id: aws.elasticsearch.domains
      x-cfn-schema-name: Domain
      x-type: list
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Elasticsearch::Domain'
    domain:
      name: domain
      id: aws.elasticsearch.domain
      x-cfn-schema-name: Domain
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ElasticsearchClusterConfig') as elasticsearch_cluster_config,
              JSON_EXTRACT(Properties, '$.DomainName') as domain_name,
              JSON_EXTRACT(Properties, '$.ElasticsearchVersion') as elasticsearch_version,
              JSON_EXTRACT(Properties, '$.LogPublishingOptions') as log_publishing_options,
              JSON_EXTRACT(Properties, '$.SnapshotOptions') as snapshot_options,
              JSON_EXTRACT(Properties, '$.VPCOptions') as v_pc_options,
              JSON_EXTRACT(Properties, '$.NodeToNodeEncryptionOptions') as node_to_node_encryption_options,
              JSON_EXTRACT(Properties, '$.AccessPolicies') as access_policies,
              JSON_EXTRACT(Properties, '$.DomainEndpointOptions') as domain_endpoint_options,
              JSON_EXTRACT(Properties, '$.DomainArn') as domain_arn,
              JSON_EXTRACT(Properties, '$.CognitoOptions') as cognito_options,
              JSON_EXTRACT(Properties, '$.AdvancedOptions') as advanced_options,
              JSON_EXTRACT(Properties, '$.AdvancedSecurityOptions') as advanced_security_options,
              JSON_EXTRACT(Properties, '$.DomainEndpoint') as domain_endpoint,
              JSON_EXTRACT(Properties, '$.EBSOptions') as e_bs_options,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.EncryptionAtRestOptions') as encryption_at_rest_options,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Elasticsearch::Domain'
