openapi: 3.0.0
info:
  title: Inspector
  version: 1.0.0
paths: {}
components:
  schemas:
    AssessmentTarget:
      type: object
      properties:
        Arn:
          type: string
        AssessmentTargetName:
          type: string
        ResourceGroupArn:
          type: string
      x-stackql-resource-name: assessment_target
    Tag:
      type: object
      additionalProperties: false
      properties:
        Key:
          type: string
        Value:
          type: string
      required:
        - Value
        - Key
    AssessmentTemplate:
      type: object
      properties:
        Arn:
          type: string
        AssessmentTargetArn:
          type: string
        DurationInSeconds:
          type: integer
        AssessmentTemplateName:
          type: string
        RulesPackageArns:
          type: array
          uniqueItems: false
          items:
            type: string
        UserAttributesForFindings:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - AssessmentTargetArn
        - DurationInSeconds
        - RulesPackageArns
      x-stackql-resource-name: assessment_template
    ResourceGroup:
      type: object
      properties:
        Arn:
          type: string
        ResourceGroupTags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - ResourceGroupTags
      x-stackql-resource-name: resource_group
  x-stackQL-resources:
    assessment_target:
      name: assessment_target
      id: aws.inspector.assessment_target
      x-cfn-schema-name: AssessmentTarget
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.AssessmentTargetName') as assessment_target_name,
              JSON_EXTRACT(Properties, '$.ResourceGroupArn') as resource_group_arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Inspector::AssessmentTarget' ;
    assessment_template:
      name: assessment_template
      id: aws.inspector.assessment_template
      x-cfn-schema-name: AssessmentTemplate
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.AssessmentTargetArn') as assessment_target_arn,
              JSON_EXTRACT(Properties, '$.DurationInSeconds') as duration_in_seconds,
              JSON_EXTRACT(Properties, '$.AssessmentTemplateName') as assessment_template_name,
              JSON_EXTRACT(Properties, '$.RulesPackageArns') as rules_package_arns,
              JSON_EXTRACT(Properties, '$.UserAttributesForFindings') as user_attributes_for_findings
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Inspector::AssessmentTemplate' ;
    resource_group:
      name: resource_group
      id: aws.inspector.resource_group
      x-cfn-schema-name: ResourceGroup
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.ResourceGroupTags') as resource_group_tags
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Inspector::ResourceGroup' ;
