openapi: 3.0.0
info:
  title: IoT1Click
  version: 1.0.0
paths: {}
components:
  schemas:
    Device:
      type: object
      properties:
        DeviceId:
          type: string
        Enabled:
          type: boolean
        Arn:
          type: string
      required:
        - Enabled
        - DeviceId
      x-stackql-resource-name: device
    Placement:
      type: object
      properties:
        Id:
          type: string
        PlacementName:
          type: string
        ProjectName:
          type: string
        AssociatedDevices:
          type: object
        Attributes:
          type: object
      required:
        - ProjectName
      x-stackql-resource-name: placement
    PlacementTemplate:
      type: object
      additionalProperties: false
      properties:
        DeviceTemplates:
          type: object
        DefaultAttributes:
          type: object
    Project:
      type: object
      properties:
        Id:
          type: string
        ProjectName:
          type: string
        Arn:
          type: string
        Description:
          type: string
        PlacementTemplate:
          $ref: '#/components/schemas/PlacementTemplate'
      required:
        - PlacementTemplate
      x-stackql-resource-name: project
  x-stackQL-resources:
    device:
      name: device
      id: aws.iot1click.device
      x-cfn-schema-name: Device
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.DeviceId') as device_id,
              JSON_EXTRACT(Properties, '$.Enabled') as enabled,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::IoT1Click::Device' ;
    placement:
      name: placement
      id: aws.iot1click.placement
      x-cfn-schema-name: Placement
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.PlacementName') as placement_name,
              JSON_EXTRACT(Properties, '$.ProjectName') as project_name,
              JSON_EXTRACT(Properties, '$.AssociatedDevices') as associated_devices,
              JSON_EXTRACT(Properties, '$.Attributes') as attributes
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::IoT1Click::Placement' ;
    project:
      name: project
      id: aws.iot1click.project
      x-cfn-schema-name: Project
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.ProjectName') as project_name,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.PlacementTemplate.DeviceTemplates') as placement_template_device_templates,
              JSON_EXTRACT(Properties, '$.PlacementTemplate.DefaultAttributes') as placement_template_default_attributes
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::IoT1Click::Project' ;
