openapi: 3.0.0
info:
  title: IoTThingsGraph
  version: 1.0.0
paths: {}
components:
  schemas:
    DefinitionDocument:
      type: object
      additionalProperties: false
      properties:
        Language:
          type: string
        Text:
          type: string
      required:
        - Language
        - Text
    FlowTemplate:
      type: object
      properties:
        Id:
          type: string
        CompatibleNamespaceVersion:
          type: number
        Definition:
          $ref: '#/components/schemas/DefinitionDocument'
      required:
        - Definition
      x-stackql-resource-name: flow_template
  x-stackQL-resources:
    flow_template:
      name: flow_template
      id: aws.iotthingsgraph.flow_template
      x-cfn-schema-name: FlowTemplate
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.CompatibleNamespaceVersion') as compatible_namespace_version,
              JSON_EXTRACT(Properties, '$.Definition.Language') as definition_language,
              JSON_EXTRACT(Properties, '$.Definition.Text') as definition_text
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::IoTThingsGraph::FlowTemplate' ;
