openapi: 3.0.0
info:
  title: IVS
  version: 1.0.0
paths: {}
components:
  schemas:
    Tag:
      description: A key-value pair to associate with a resource.
      type: object
      additionalProperties: false
      properties:
        Key:
          type: string
          description: 'The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
          minLength: 1
          maxLength: 128
        Value:
          type: string
          description: 'The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
          minLength: 1
          maxLength: 256
      required:
        - Value
        - Key
    Channel:
      type: object
      properties:
        Arn:
          description: Channel ARN is automatically generated on creation and assigned as the unique identifier.
          type: string
          pattern: ^arn:aws:ivs:[a-z0-9-]+:[0-9]+:channel/[a-zA-Z0-9-]+$
          minLength: 1
          maxLength: 128
        Name:
          description: Channel
          type: string
          minLength: 0
          maxLength: 128
          pattern: ^[a-zA-Z0-9-_]*$
          default: '-'
        Authorized:
          description: Whether the channel is authorized.
          type: boolean
          default: false
        LatencyMode:
          description: Channel latency mode.
          type: string
          enum:
            - NORMAL
            - LOW
          default: LOW
        Type:
          description: Channel type, which determines the allowable resolution and bitrate. If you exceed the allowable resolution or bitrate, the stream probably will disconnect immediately.
          type: string
          enum:
            - STANDARD
            - BASIC
          default: STANDARD
        Tags:
          description: A list of key-value pairs that contain metadata for the asset model.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          maxItems: 50
          items:
            $ref: '#/components/schemas/Tag'
        PlaybackUrl:
          description: Channel Playback URL.
          type: string
        IngestEndpoint:
          description: Channel ingest endpoint, part of the definition of an ingest server, used when you set up streaming software.
          type: string
        RecordingConfigurationArn:
          description: 'Recording Configuration ARN. A value other than an empty string indicates that recording is enabled. Default: "" (recording is disabled).'
          type: string
          default: ''
          pattern: ^$|arn:aws:ivs:[a-z0-9-]+:[0-9]+:recording-configuration/[a-zA-Z0-9-]+$
          minLength: 0
          maxLength: 128
      required: []
      x-stackql-resource-name: channel
    PlaybackKeyPair:
      type: object
      properties:
        Name:
          description: An arbitrary string (a nickname) assigned to a playback key pair that helps the customer identify that resource. The value does not need to be unique.
          type: string
          pattern: ^[a-zA-Z0-9-_]*$
          minLength: 0
          maxLength: 128
        PublicKeyMaterial:
          description: The public portion of a customer-generated key pair.
          type: string
        Fingerprint:
          description: Key-pair identifier.
          type: string
        Arn:
          description: Key-pair identifier.
          type: string
          pattern: ^arn:aws:ivs:[a-z0-9-]+:[0-9]+:playback-key/[a-zA-Z0-9-]+$
          minLength: 1
          maxLength: 128
        Tags:
          description: A list of key-value pairs that contain metadata for the asset model.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          maxItems: 50
          items:
            $ref: '#/components/schemas/Tag'
      x-stackql-resource-name: playback_key_pair
    DestinationConfiguration:
      description: Destination configuration for IVS Chat logging.
      type: object
      additionalProperties: false
      properties:
        CloudWatchLogs:
          $ref: '#/components/schemas/CloudWatchLogsDestinationConfiguration'
        Firehose:
          $ref: '#/components/schemas/FirehoseDestinationConfiguration'
        S3:
          $ref: '#/components/schemas/S3DestinationConfiguration'
      required: []
    S3DestinationConfiguration:
      description: S3 destination configuration for IVS Chat logging.
      type: object
      additionalProperties: false
      properties:
        BucketName:
          description: Name of the Amazon S3 bucket where chat activity will be logged.
          type: string
          pattern: ^[a-z0-9-.]+$
          minLength: 3
          maxLength: 63
      required:
        - BucketName
    ThumbnailConfiguration:
      description: Recording Thumbnail Configuration.
      type: object
      additionalProperties: false
      properties:
        RecordingMode:
          description: Thumbnail Recording Mode, which determines whether thumbnails are recorded at an interval or are disabled.
          type: string
          enum:
            - INTERVAL
            - DISABLED
        TargetIntervalSeconds:
          description: Thumbnail recording Target Interval Seconds defines the interval at which thumbnails are recorded. This field is required if RecordingMode is INTERVAL.
          type: integer
          minimum: 5
          maximum: 60
      required:
        - RecordingMode
    RecordingConfiguration:
      type: object
      properties:
        Arn:
          description: Recording Configuration ARN is automatically generated on creation and assigned as the unique identifier.
          type: string
          pattern: ^arn:aws[-a-z]*:ivs:[a-z0-9-]+:[0-9]+:recording-configuration/[a-zA-Z0-9-]+$
          minLength: 1
          maxLength: 128
        Name:
          description: Recording Configuration Name.
          type: string
          minLength: 0
          maxLength: 128
          pattern: ^[a-zA-Z0-9-_]*$
        State:
          description: Recording Configuration State.
          type: string
          enum:
            - CREATING
            - CREATE_FAILED
            - ACTIVE
        RecordingReconnectWindowSeconds:
          description: Recording Reconnect Window Seconds. (0 means disabled)
          type: integer
          default: 0
          minimum: 0
          maximum: 300
        DestinationConfiguration:
          $ref: '#/components/schemas/DestinationConfiguration'
        Tags:
          description: A list of key-value pairs that contain metadata for the asset model.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          maxItems: 50
          items:
            $ref: '#/components/schemas/Tag'
        ThumbnailConfiguration:
          $ref: '#/components/schemas/ThumbnailConfiguration'
      required:
        - DestinationConfiguration
      x-stackql-resource-name: recording_configuration
    StreamKey:
      type: object
      properties:
        Arn:
          description: Stream Key ARN is automatically generated on creation and assigned as the unique identifier.
          type: string
          pattern: ^arn:aws:ivs:[a-z0-9-]+:[0-9]+:stream-key/[a-zA-Z0-9-]+$
          minLength: 1
          maxLength: 128
        ChannelArn:
          description: Channel ARN for the stream.
          type: string
          pattern: ^arn:aws:ivs:[a-z0-9-]+:[0-9]+:channel/[a-zA-Z0-9-]+$
        Tags:
          description: A list of key-value pairs that contain metadata for the asset model.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          maxItems: 50
          items:
            $ref: '#/components/schemas/Tag'
        Value:
          description: Stream-key value.
          type: string
      required:
        - ChannelArn
      x-stackql-resource-name: stream_key
    CloudWatchLogsDestinationConfiguration:
      description: CloudWatch destination configuration for IVS Chat logging.
      type: object
      additionalProperties: false
      properties:
        LogGroupName:
          description: Name of the Amazon CloudWatch Logs log group where chat activity will be logged.
          type: string
          pattern: ^[\.\-_/#A-Za-z0-9]+$
          minLength: 1
          maxLength: 512
      required:
        - LogGroupName
    FirehoseDestinationConfiguration:
      description: Kinesis Firehose destination configuration for IVS Chat logging.
      type: object
      additionalProperties: false
      properties:
        DeliveryStreamName:
          description: Name of the Amazon Kinesis Firehose delivery stream where chat activity will be logged.
          type: string
          pattern: ^[a-zA-Z0-9_.-]+$
          minLength: 1
          maxLength: 64
      required:
        - DeliveryStreamName
    LoggingConfiguration:
      type: object
      properties:
        Arn:
          description: LoggingConfiguration ARN is automatically generated on creation and assigned as the unique identifier.
          type: string
          pattern: ^arn:aws:ivschat:[a-z0-9-]+:[0-9]+:logging-configuration/[a-zA-Z0-9-]+$
          minLength: 1
          maxLength: 128
        Id:
          description: The system-generated ID of the logging configuration.
          type: string
          pattern: ^[a-zA-Z0-9]+$
          minLength: 12
          maxLength: 12
        DestinationConfiguration:
          $ref: '#/components/schemas/DestinationConfiguration'
        Name:
          description: The name of the logging configuration. The value does not need to be unique.
          type: string
          pattern: ^[a-zA-Z0-9-_]*$
          minLength: 0
          maxLength: 128
        State:
          description: The state of the logging configuration. When the state is ACTIVE, the configuration is ready to log chat content.
          type: string
          enum:
            - CREATING
            - CREATE_FAILED
            - DELETING
            - DELETE_FAILED
            - UPDATING
            - UPDATING_FAILED
            - ACTIVE
        Tags:
          description: An array of key-value pairs to apply to this resource.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - DestinationConfiguration
      x-stackql-resource-name: logging_configuration
    MessageReviewHandler:
      description: Configuration information for optional review of messages.
      type: object
      additionalProperties: false
      properties:
        FallbackResult:
          description: Specifies the fallback behavior if the handler does not return a valid response, encounters an error, or times out.
          type: string
          enum:
            - ALLOW
            - DENY
          default: ALLOW
        Uri:
          description: Identifier of the message review handler.
          type: string
          pattern: ^$|^arn:aws:lambda:[a-z0-9-]+:[0-9]{12}:function:.+
          minLength: 0
          maxLength: 170
      required: []
    Room:
      type: object
      properties:
        Arn:
          description: Room ARN is automatically generated on creation and assigned as the unique identifier.
          type: string
          pattern: ^arn:aws:ivschat:[a-z0-9-]+:[0-9]+:room/[a-zA-Z0-9-]+$
          minLength: 1
          maxLength: 128
        Id:
          description: The system-generated ID of the room.
          type: string
          pattern: ^[a-zA-Z0-9]+$
          minLength: 12
          maxLength: 12
        Name:
          description: The name of the room. The value does not need to be unique.
          type: string
          pattern: ^[a-zA-Z0-9-_]*$
          minLength: 0
          maxLength: 128
        LoggingConfigurationIdentifiers:
          description: Array of logging configuration identifiers attached to the room.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          minItems: 0
          maxItems: 50
          items:
            type: string
            pattern: ^arn:aws:ivschat:[a-z0-9-]+:[0-9]+:logging-configuration/[a-zA-Z0-9-]+$
            minLength: 1
            maxLength: 128
        MaximumMessageLength:
          description: The maximum number of characters in a single message.
          type: integer
          minimum: 1
          maximum: 500
          default: 500
        MaximumMessageRatePerSecond:
          description: The maximum number of messages per second that can be sent to the room.
          type: integer
          minimum: 1
          maximum: 10
          default: 10
        MessageReviewHandler:
          $ref: '#/components/schemas/MessageReviewHandler'
        Tags:
          description: An array of key-value pairs to apply to this resource.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
      required: []
      x-stackql-resource-name: room
  x-stackQL-resources:
    channel:
      name: channel
      id: aws.ivs.channel
      x-cfn-schema-name: Channel
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Authorized') as authorized,
              JSON_EXTRACT(Properties, '$.LatencyMode') as latency_mode,
              JSON_EXTRACT(Properties, '$.Type') as type,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.PlaybackUrl') as playback_url,
              JSON_EXTRACT(Properties, '$.IngestEndpoint') as ingest_endpoint,
              JSON_EXTRACT(Properties, '$.RecordingConfigurationArn') as recording_configuration_arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::IVS::Channel' ;
    playback_key_pair:
      name: playback_key_pair
      id: aws.ivs.playback_key_pair
      x-cfn-schema-name: PlaybackKeyPair
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.PublicKeyMaterial') as public_key_material,
              JSON_EXTRACT(Properties, '$.Fingerprint') as fingerprint,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::IVS::PlaybackKeyPair' ;
    recording_configuration:
      name: recording_configuration
      id: aws.ivs.recording_configuration
      x-cfn-schema-name: RecordingConfiguration
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.State') as state,
              JSON_EXTRACT(Properties, '$.RecordingReconnectWindowSeconds') as recording_reconnect_window_seconds,
              JSON_EXTRACT(Properties, '$.DestinationConfiguration.CloudWatchLogs') as destination_configuration_cloud_watch_logs,
              JSON_EXTRACT(Properties, '$.DestinationConfiguration.Firehose') as destination_configuration_firehose,
              JSON_EXTRACT(Properties, '$.DestinationConfiguration.S3') as destination_configuration_s3,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.ThumbnailConfiguration.RecordingMode') as thumbnail_configuration_recording_mode,
              JSON_EXTRACT(Properties, '$.ThumbnailConfiguration.TargetIntervalSeconds') as thumbnail_configuration_target_interval_seconds
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::IVS::RecordingConfiguration' ;
    stream_key:
      name: stream_key
      id: aws.ivs.stream_key
      x-cfn-schema-name: StreamKey
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.ChannelArn') as channel_arn,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.Value') as value
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::IVS::StreamKey' ;
    logging_configuration:
      name: logging_configuration
      id: aws.ivs.logging_configuration
      x-cfn-schema-name: LoggingConfiguration
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.DestinationConfiguration.CloudWatchLogs') as destination_configuration_cloud_watch_logs,
              JSON_EXTRACT(Properties, '$.DestinationConfiguration.Firehose') as destination_configuration_firehose,
              JSON_EXTRACT(Properties, '$.DestinationConfiguration.S3') as destination_configuration_s3,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.State') as state,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::IVS::LoggingConfiguration' ;
    room:
      name: room
      id: aws.ivs.room
      x-cfn-schema-name: Room
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.LoggingConfigurationIdentifiers') as logging_configuration_identifiers,
              JSON_EXTRACT(Properties, '$.MaximumMessageLength') as maximum_message_length,
              JSON_EXTRACT(Properties, '$.MaximumMessageRatePerSecond') as maximum_message_rate_per_second,
              JSON_EXTRACT(Properties, '$.MessageReviewHandler.FallbackResult') as message_review_handler_fallback_result,
              JSON_EXTRACT(Properties, '$.MessageReviewHandler.Uri') as message_review_handler_uri,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::IVS::Room' ;
