openapi: 3.0.0
info:
  title: LookoutVision
  version: 1.0.0
paths: {}
components:
  schemas:
    Arn:
      type: string
      maxLength: 1000
    ProjectName:
      description: The name of the Amazon Lookout for Vision project
      type: string
      minLength: 1
      maxLength: 255
      pattern: '[a-zA-Z0-9][a-zA-Z0-9_\-]*'
    Project:
      type: object
      properties:
        Arn:
          $ref: '#/components/schemas/Arn'
        ProjectName:
          $ref: '#/components/schemas/ProjectName'
      required:
        - ProjectName
      x-stackql-resource-name: project
  x-stackQL-resources:
    project:
      name: project
      id: aws.lookoutvision.project
      x-cfn-schema-name: Project
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::LookoutVision::Project' ;
