openapi: 3.0.0
info:
  title: ResourceExplorer2
  version: 1.0.0
paths: {}
components:
  schemas:
    DefaultViewAssociation:
      type: object
      properties:
        ViewArn:
          type: string
        AssociatedAwsPrincipal:
          description: The AWS principal that the default view is associated with, used as the unique identifier for this resource.
          type: string
          pattern: ^[0-9]{12}$
      required:
        - ViewArn
      x-stackql-resource-name: default_view_association
      x-stackql-primaryIdentifier:
        - AssociatedAwsPrincipal
      x-read-only-properties:
        - AssociatedAwsPrincipal
      x-required-permissions:
        create:
          - resource-explorer-2:GetDefaultView
          - resource-explorer-2:AssociateDefaultView
        update:
          - resource-explorer-2:GetDefaultView
          - resource-explorer-2:AssociateDefaultView
        read:
          - resource-explorer-2:GetDefaultView
        delete:
          - resource-explorer-2:GetDefaultView
          - resource-explorer-2:DisassociateDefaultView
    IndexType:
      type: string
      enum:
        - LOCAL
        - AGGREGATOR
    TagMap:
      type: object
      x-patternProperties:
        .+:
          type: string
      additionalProperties: false
    IndexState:
      type: string
      enum:
        - ACTIVE
        - CREATING
        - DELETING
        - DELETED
        - UPDATING
    Index:
      type: object
      properties:
        Arn:
          type: string
        Tags:
          $ref: '#/components/schemas/TagMap'
        Type:
          $ref: '#/components/schemas/IndexType'
        IndexState:
          $ref: '#/components/schemas/IndexState'
      required:
        - Type
      x-stackql-resource-name: index
      x-stackql-primaryIdentifier:
        - Arn
      x-read-only-properties:
        - Arn
        - IndexState
      x-required-permissions:
        create:
          - resource-explorer-2:CreateIndex
          - resource-explorer-2:GetIndex
          - resource-explorer-2:TagResource
          - resource-explorer-2:UpdateIndexType
          - resource-explorer-2:DeleteIndex
          - iam:CreateServiceLinkedRole
        update:
          - resource-explorer-2:GetIndex
          - resource-explorer-2:UpdateIndexType
          - resource-explorer-2:TagResource
          - resource-explorer-2:UntagResource
          - resource-explorer-2:ListTagsForResource
        delete:
          - resource-explorer-2:DeleteIndex
          - resource-explorer-2:GetIndex
          - resource-explorer-2:UntagResource
        list:
          - resource-explorer-2:ListIndexes
        read:
          - resource-explorer-2:GetIndex
    IncludedProperty:
      type: object
      properties:
        Name:
          type: string
          maxLength: 1011
          minLength: 1
      required:
        - Name
      additionalProperties: false
    SearchFilter:
      type: object
      properties:
        FilterString:
          type: string
          maxLength: 2048
          minLength: 0
      required:
        - FilterString
      additionalProperties: false
    View:
      type: object
      properties:
        Filters:
          $ref: '#/components/schemas/SearchFilter'
        IncludedProperties:
          type: array
          items:
            $ref: '#/components/schemas/IncludedProperty'
        Scope:
          type: string
        Tags:
          $ref: '#/components/schemas/TagMap'
        ViewArn:
          type: string
        ViewName:
          type: string
          pattern: ^[a-zA-Z0-9\-]{1,64}$
      required:
        - ViewName
      x-stackql-resource-name: view
      x-stackql-primaryIdentifier:
        - ViewArn
      x-create-only-properties:
        - Scope
        - ViewName
      x-read-only-properties:
        - ViewArn
      x-required-permissions:
        create:
          - resource-explorer-2:CreateView
          - resource-explorer-2:TagResource
        read:
          - resource-explorer-2:GetView
        update:
          - resource-explorer-2:UpdateView
          - resource-explorer-2:TagResource
          - resource-explorer-2:UntagResource
          - resource-explorer-2:ListTagsForResource
        delete:
          - resource-explorer-2:DeleteView
          - resource-explorer-2:GetView
          - resource-explorer-2:UntagResource
        list:
          - resource-explorer-2:ListViews
  x-stackQL-resources:
    default_view_associations:
      name: default_view_associations
      id: aws.resourceexplorer2.default_view_associations
      x-cfn-schema-name: DefaultViewAssociation
      x-type: list
      x-identifiers:
        - AssociatedAwsPrincipal
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.AssociatedAwsPrincipal') as associated_aws_principal
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::ResourceExplorer2::DefaultViewAssociation'
    default_view_association:
      name: default_view_association
      id: aws.resourceexplorer2.default_view_association
      x-cfn-schema-name: DefaultViewAssociation
      x-type: get
      x-identifiers:
        - AssociatedAwsPrincipal
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ViewArn') as view_arn,
              JSON_EXTRACT(Properties, '$.AssociatedAwsPrincipal') as associated_aws_principal
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::ResourceExplorer2::DefaultViewAssociation'
    indices:
      name: indices
      id: aws.resourceexplorer2.indices
      x-cfn-schema-name: Index
      x-type: list
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::ResourceExplorer2::Index'
    index:
      name: index
      id: aws.resourceexplorer2.index
      x-cfn-schema-name: Index
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.Type') as type,
              JSON_EXTRACT(Properties, '$.IndexState') as index_state
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::ResourceExplorer2::Index'
    views:
      name: views
      id: aws.resourceexplorer2.views
      x-cfn-schema-name: View
      x-type: list
      x-identifiers:
        - ViewArn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ViewArn') as view_arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::ResourceExplorer2::View'
    view:
      name: view
      id: aws.resourceexplorer2.view
      x-cfn-schema-name: View
      x-type: get
      x-identifiers:
        - ViewArn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Filters') as filters,
              JSON_EXTRACT(Properties, '$.IncludedProperties') as included_properties,
              JSON_EXTRACT(Properties, '$.Scope') as scope,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.ViewArn') as view_arn,
              JSON_EXTRACT(Properties, '$.ViewName') as view_name
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::ResourceExplorer2::View'
