openapi: 3.0.0
info:
  title: SDB
  version: 1.0.0
paths: {}
components:
  schemas:
    Domain:
      type: object
      properties:
        Id:
          type: string
        Description:
          type: string
      x-stackql-resource-name: domain
  x-stackQL-resources:
    domain:
      name: domain
      id: aws.sdb.domain
      x-cfn-schema-name: Domain
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Description') as description
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::SDB::Domain' ;
