openapi: 3.0.0
info:
  title: SecurityHub
  version: 1.0.0
paths: {}
components:
  schemas:
    Hub:
      type: object
      properties:
        Id:
          type: string
        Tags:
          type: object
      x-stackql-resource-name: hub
  x-stackQL-resources:
    hub:
      name: hub
      id: aws.securityhub.hub
      x-cfn-schema-name: Hub
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::SecurityHub::Hub' ;
